Repository iu7dreamteam/Movie-quotes-frontend, pull requests merged in 2021-05, with the labels that each got.

#14 Feature/layout improvemets mq 41
  assets/default/poster.png
  package-lock.json
  src/components/History.js
  src/components/Homepage.js
  src/components/Match.js
  src/components/MatchList.js
  src/components/Navbar.js
  src/components/Player.js
  src/components/SignIn.js
  src/components/Signup.js
  src/components/Theater.js
  src/components/TimeCode.js
  src/components/TimeCodeList.js
  src/styles/App.css
  src/styles/Homepage.css
  src/utility/text/truncateIfOver.js
Labels: enhancement

#15 Feature/login view mq 44
  package-lock.json
  package.json
  src/actions/error.js
  src/actions/index.js
  src/actions/loading.js
  src/actions/user.js
  src/components/App.js
  src/components/Loadingpage.js
  src/components/Navbar.js
  src/components/SignIn.js
  src/components/SignUp.js
  src/config/index.js
  src/constants/ActionTypes.js
  src/index.js
  src/reducers/error.js
  src/reducers/index.js
  src/reducers/isLoading.js
  src/reducers/user.js
  src/store.js
  src/utility/memory/cookies.js
  src/utility/memory/user.js
  src/utility/response/index.js
  src/views/App.js
  src/views/Navbar.js
  src/views/SignIn.js
  webpack.config.js
Labels: enhancement

#16 Bugfix/loading page mq 48
  src/actions/user.js
  src/components/App.js
  src/components/EmailField.js
  src/components/EntryField.js
  src/components/Loadingpage.js
  src/components/PasswordField.js
  src/components/SignIn.js
  src/components/UsernameField.js
  src/reducers/isLoading.js
  src/styles/App.css
Labels: bug

#17 MQ-49: fill Theater view according to searchResult
  src/actions/index.js
  src/actions/matches.js
  src/components/App.js
  src/components/Homepage.js
  src/components/Match.js
  src/components/Navbar.js
  src/components/Theater.js
  src/components/TimeCode.js
  src/components/TimeCodeList.js
  src/constants/ActionTypes.js
  src/reducers/index.js
  src/reducers/searchResult.js
  src/views/Theater.js
Labels: enhancement

#19 MQ-47: Add signup-view
  package-lock.json
  src/actions/user.js
  src/components/App.js
  src/components/SignUp.js
  src/views/SignUp.js
Labels: feature
